tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
  - init: |
      pyenv install 3.10.5
      pyenv global 3.10.5

      pip install pdm
      pdm install
    command: |
      pdm import-feeds
      pdm migrate
      pdm dev

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
