tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
  - init: |
      pyenv install 3.10.5
      pyenv global 3.10.5

      pip install poetry
      poetry config virtualenvs.create true
      poetry config virtualenvs.in-project true
      poetry env use python
      poetry install
    command: |
      poetry run poe import-data
      poetry run poe migrate
      poetry run poe server

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
