repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit

    rev: "v0.0.261"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pdm-project/pdm
    rev: 2.5.2
    hooks:
      - id: pdm-export
        # command arguments, e.g.:
        args: ["-o", "requirements.txt", "--without-hashes"]
        files: ^pdm.lock$
